# Generated by Django 5.0.3 on 2024-03-16 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_profession'),
        ('vacancy', '0002_vacancyapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyapplication',
            name='resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.resume'),
            preserve_default=False,
        ),
    ]
