# Generated by Django 5.0.3 on 2024-03-14 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_of_birth', models.DateField()),
                ('citizenship', models.CharField(blank=True, max_length=100, null=True)),
                ('education_level', models.CharField(choices=[('secondary', 'Secondary'), ('specialized secondary', 'Specialized secondary'), ('higher', 'Higher')], max_length=100)),
                ('name_of_institution', models.CharField(max_length=255)),
                ('about_your_self', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
    ]
