# Generated by Django 5.0.3 on 2024-03-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profession',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
